
  version: '3.8'

  services:
    postgres:
      image: postgres:latest
      container_name: liter-alura
      environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: literalura
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
  volumes:
    db_data: